# Site
name: 'ASN'
description: 'AirsoftNorge.com is a site for the dissemination of information and media within the Norwegian airsoft community.'
logo: 'assets/graphics/asn-logo-v1.png'
favicon: 'assets/graphics/favicon.ico'
baseurl: 'https://airsoftnorge.github.io/mundana/'
email: 'staff.airsoftnorge@gmail.com'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    staff:
      name:           Staff
      site:           https://www.airsoftnorge.com
      avatar:         /assets/graphics/avatars/avatar_asn.png
      bio:            "Default account for generic content."
      email:          staff.airsoftnorge@gmail.com
      facebook:       https://www.facebook.com/AirsoftNorge
      discord:        https://discord.gg/gMegmXMAPN
      youtube:        https://www.youtube.com/channel/UC0jdeJCXXosXPuwOcTH1MAA
      
    adakar:
      name:           AdakaR
      site:           https://www.airsoftnorge.com
      avatar:         /assets/graphics/avatars/avatar_flode.png
      bio:            "Might be a stuffed animal.."
      facebook:       https://www.facebook.com/FlodeKomodeMedTyttebaerIHodet
      
    ulfhednar:
      name:           Ulfhednar
      site:           https://www.airsoftnorge.com
      facebook:       https://www.facebook.com/ulfhednarmilsim
      avatar:         /assets/graphics/avatars/avatar_ulfhednar_grid.png
      bio:            "Airsofter and collector since 2007. Incurable gearwhore, with a proclivity for helmets, NV mounts and Ranger Green."
   

 

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: staff
      avatar: /assets/images/avatar_asn.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 12



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, _cheatsheet.md]
