# Site
name: 'ASN'
description: 'AirsoftNorge.com is a site for the dissemination of information and media within the Norwegian airsoft community.'
logo: 'assets/graphics/asn-logo-45px.png'
favicon: 'assets/graphics/favicon.ico'
baseurl: 'https://airsoftnorge.github.io/mundana/'
email: 'staff.airsoftnorge@gmail.com'


include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:

    staff:
      name:           Staff
      site:           https://www.airsoftnorge.com
      avatar:         /assets/graphics/avatars/avatar_asn.png
      bio:            "Posts and announcements from members of AirsoftNorge staff."
      email:          staff.airsoftnorge@gmail.com
      #github:         https://github.com/airsoftnorge
      facebook:       https://www.facebook.com/AirsoftNorge
      discord:        https://discord.gg/gMegmXMAPN
      youtube:        https://www.youtube.com/channel/UC0jdeJCXXosXPuwOcTH1MAA
      
    adakar:
      name:           AdakaR
      site:           https://www.airsoftnorge.com
      avatar:         /assets/graphics/avatars/avatar_flode.png
      bio:            "More than 15 years of experience in airsoft. Former member of Stor-Oslo Airsoftklubb (SOAK)."
      #github:         https://github.com/skadakar
      facebook:       https://www.facebook.com/FlodeKomodeMedTyttebaerIHodet
      
    ulfhednar:
      name:           Ulfhednar
      site:           https://www.airsoftnorge.com
      facebook:       https://www.facebook.com/ulfhednarmilsim
      avatar:         /assets/graphics/avatars/avatar_ulfhednar_grid.png
      bio:            "15 years of experience as an airsofter and collector of military equipment, with a proclivity for helmets, all things H&K and Ranger Green. Former member of Møre og Romsdal Airsoft. (MRA)."
   

 

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: staff
      avatar: /assets/images/avatar_asn.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 12



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, _cheatsheet.md, 2022-01-22-residual-energy-calculator.md]
